//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCarta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Voice3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voice3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFCarta.Voice3", typeof(Voice3).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00432 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00432", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00433 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00433", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00434 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00434", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00435 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00435", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00436 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00436", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00437 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00437", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00438 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00438", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00439 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00439", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00440 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00440", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00441 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00441", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00442 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00442", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00443 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00443", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00444 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00444", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00445 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00445", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00446 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00446", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00447 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00447", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00448 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00448", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00449 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00449", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00450 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00450", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00451 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00451", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00452 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00452", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00453 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00453", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00454 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00454", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00455 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00455", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00456 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00456", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00457 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00457", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00458 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00458", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00459 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00459", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00460 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00460", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00461 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00461", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00462 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00462", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00463 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00463", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00464 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00464", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00465 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00465", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00466 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00466", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00467 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00467", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00468 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00468", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00469 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00469", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00470 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00470", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00471 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00471", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00472 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00472", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00473 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00473", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00474 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00474", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00475 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00475", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00476 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00476", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00477 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00477", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00478 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00478", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00479 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00479", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00480 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00480", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00481 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00481", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00482 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00482", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00483 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00483", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00484 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00484", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00485 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00485", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00486 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00486", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00487 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00487", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00488 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00488", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00489 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00489", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00490 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00490", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00491 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00491", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00492 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00492", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00493 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00493", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00494 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00494", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00495 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00495", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00496 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00496", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00497 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00497", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00498 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00498", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00499 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00499", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00500 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00501 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00501", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00502 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00502", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00503 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00503", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00504 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00504", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00505 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00505", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00506 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00506", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00507 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00507", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00508 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00508", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00509 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00509", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00510 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00510", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00511 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00511", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00512 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00512", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00513 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00513", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00514 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00514", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00515 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00515", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00516 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00516", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00517 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00517", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00518 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00518", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00519 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00519", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00520 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00520", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00521 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00521", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00522 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00522", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00523 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00523", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00524 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00524", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00525 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00525", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00526 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00526", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00527 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00527", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00528 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00528", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00529 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00529", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00530 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00530", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00531 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00531", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00692 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00692", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00693 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00693", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00694 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00694", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00695 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00695", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00696 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00696", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00697 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00697", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00698 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00698", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00699 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00699", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00700 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00700", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00701 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00701", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00702 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00702", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00703 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00703", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00704 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00704", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00705 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00705", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00706 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00706", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00707 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00707", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00708 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00708", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00709 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00709", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00710 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00710", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00711 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00711", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00712 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00712", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00713 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00713", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00714 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00714", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00715 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00715", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00716 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00716", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00717 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00717", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00718 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00718", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00719 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00719", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00720 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00720", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00721 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00721", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00722 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00722", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00723 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00723", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00724 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00724", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00725 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00725", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00726 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00726", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00727 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00727", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00728 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00728", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00729 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00729", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00730 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00730", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00731 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00731", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00732 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00732", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00733 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00733", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00734 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00734", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00735 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00735", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00736 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00736", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00737 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00737", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00738 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00738", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00739 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00739", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00740 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00740", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00741 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00741", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00742 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00742", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00743 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00743", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00744 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00744", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00745 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00745", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00746 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00746", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00747 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00747", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00748 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00748", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00749 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00749", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00750 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00750", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00751 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00751", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00752 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00752", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00753 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00753", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00754 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00754", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00755 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00755", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00756 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00756", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00757 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00757", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00758 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00758", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00759 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00759", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00760 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00760", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00761 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00761", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00762 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00762", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00763 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00763", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00764 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00764", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00765 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00765", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00766 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00766", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00767 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00767", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00768 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00768", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00769 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00769", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00770 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00770", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00771 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00771", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
