//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCarta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Voice1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voice1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFCarta.Voice1", typeof(Voice1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00232 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00232", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00233 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00233", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00234 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00234", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00235 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00235", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00236 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00236", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00237 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00237", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00238 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00238", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00239 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00239", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00240 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00240", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00241 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00241", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00242 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00242", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00243 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00243", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00244 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00244", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00245 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00245", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00246 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00246", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00247 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00247", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00248 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00248", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00249 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00249", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00250 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00250", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00251 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00251", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00252 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00252", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00253 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00253", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00254 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00254", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00255 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00255", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00256 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00256", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00257 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00257", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00258 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00258", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00259 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00259", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00260 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00260", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00261 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00261", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00262 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00262", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00263 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00263", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00264 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00264", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00265 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00265", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00266 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00266", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00267 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00267", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00268 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00268", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00269 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00269", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00270 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00270", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00271 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00271", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00272 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00272", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00273 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00273", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00274 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00274", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00275 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00275", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00276 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00276", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00277 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00277", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00278 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00278", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00279 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00279", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00280 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00280", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00281 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00281", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00282 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00282", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00283 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00283", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00284 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00284", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00285 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00285", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00286 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00286", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00287 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00287", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00288 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00288", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00289 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00289", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00290 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00290", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00291 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00291", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00292 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00292", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00293 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00293", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00294 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00294", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00295 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00295", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00296 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00296", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00297 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00297", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00298 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00298", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00299 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00299", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00300 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00301 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00301", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00302 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00302", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00303 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00303", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00304 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00304", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00305 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00305", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00306 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00306", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00307 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00307", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00308 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00308", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00309 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00309", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00310 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00310", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00311 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00311", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00312 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00312", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00313 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00313", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00314 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00314", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00315 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00315", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00316 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00316", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00317 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00317", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00318 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00318", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00319 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00319", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00320 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00320", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00321 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00321", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00322 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00322", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00323 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00323", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00324 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00324", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00325 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00325", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00326 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00326", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00327 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00327", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00328 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00328", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00329 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00329", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00330 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00330", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00331 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00331", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00532 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00532", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00533 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00533", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00534 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00534", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00535 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00535", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00536 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00536", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00537 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00537", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00538 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00538", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00539 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00539", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00540 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00540", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00541 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00541", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00542 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00542", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00543 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00543", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00544 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00544", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00545 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00545", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00546 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00546", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00547 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00547", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00548 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00548", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00549 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00549", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00550 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00550", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00551 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00551", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00552 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00552", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00553 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00553", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00554 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00554", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00555 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00555", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00556 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00556", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00557 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00557", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00558 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00558", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00559 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00559", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00560 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00560", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00561 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00561", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00562 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00562", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00563 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00563", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00564 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00564", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00565 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00565", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00566 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00566", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00567 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00567", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00568 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00568", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00569 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00569", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00570 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00570", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00571 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00571", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00572 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00572", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00573 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00573", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00574 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00574", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00575 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00575", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00576 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00576", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00577 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00577", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00578 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00578", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00579 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00579", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00580 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00580", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00581 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00581", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00582 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00582", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00583 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00583", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00584 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00584", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00585 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00585", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00586 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00586", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00587 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00587", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00588 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00588", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00589 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00589", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00590 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00590", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00591 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00591", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00592 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00592", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00593 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00593", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00594 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00594", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00595 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00595", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00596 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00596", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00597 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00597", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00598 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00598", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00599 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00599", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00600 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00600", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00601 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00601", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00602 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00602", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00603 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00603", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00604 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00604", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00605 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00605", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00606 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00606", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00607 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00607", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00608 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00608", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00609 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00609", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00610 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00610", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00611 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00611", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
