//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCarta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Voice2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Voice2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFCarta.Voice2", typeof(Voice2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00332 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00332", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00333 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00333", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00334 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00334", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00335 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00335", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00336 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00336", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00337 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00337", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00338 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00338", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00339 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00339", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00340 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00340", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00341 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00341", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00342 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00342", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00343 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00343", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00344 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00344", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00345 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00345", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00346 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00346", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00347 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00347", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00348 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00348", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00349 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00349", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00350 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00350", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00351 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00351", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00352 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00352", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00353 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00353", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00354 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00354", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00355 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00355", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00356 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00356", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00357 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00357", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00358 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00358", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00359 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00359", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00360 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00360", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00361 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00361", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00362 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00362", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00363 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00363", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00364 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00364", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00365 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00365", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00366 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00366", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00367 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00367", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00368 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00368", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00369 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00369", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00370 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00370", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00371 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00371", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00372 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00372", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00373 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00373", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00374 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00374", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00375 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00375", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00376 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00376", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00377 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00377", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00378 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00378", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00379 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00379", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00380 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00380", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00381 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00381", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00382 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00382", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00383 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00383", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00384 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00384", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00385 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00385", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00386 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00386", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00387 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00387", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00388 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00388", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00389 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00389", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00390 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00390", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00391 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00391", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00392 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00392", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00393 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00393", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00394 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00394", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00395 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00395", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00396 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00396", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00397 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00397", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00398 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00398", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00399 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00399", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00400 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00401 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00401", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00402 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00402", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00403 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00403", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00404 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00404", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00405 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00405", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00406 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00406", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00407 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00407", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00408 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00408", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00409 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00409", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00410 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00410", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00411 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00411", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00412 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00412", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00413 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00413", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00414 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00414", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00415 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00415", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00416 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00416", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00417 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00417", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00418 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00418", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00419 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00419", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00420 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00420", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00421 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00421", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00422 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00422", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00423 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00423", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00424 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00424", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00425 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00425", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00426 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00426", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00427 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00427", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00428 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00428", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00429 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00429", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00430 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00430", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00431 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00431", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00612 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00612", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00613 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00613", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00614 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00614", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00615 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00615", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00616 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00616", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00617 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00617", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00618 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00618", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00619 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00619", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00620 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00620", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00621 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00621", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00622 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00622", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00623 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00623", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00624 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00624", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00625 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00625", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00626 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00626", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00627 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00627", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00628 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00628", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00629 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00629", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00630 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00630", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00631 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00631", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00632 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00632", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00633 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00633", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00634 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00634", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00635 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00635", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00636 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00636", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00637 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00637", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00638 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00638", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00639 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00639", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00640 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00640", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00641 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00641", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00642 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00642", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00643 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00643", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00644 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00644", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00645 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00645", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00646 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00646", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00647 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00647", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00648 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00648", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00649 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00649", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00650 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00650", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00651 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00651", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00652 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00652", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00653 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00653", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00654 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00654", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00655 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00655", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00656 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00656", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00657 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00657", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00658 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00658", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00659 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00659", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00660 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00660", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00661 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00661", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00662 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00662", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00663 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00663", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00664 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00664", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00665 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00665", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00666 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00666", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00667 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00667", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00668 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00668", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00669 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00669", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00670 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00670", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00671 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00671", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00672 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00672", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00673 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00673", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00674 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00674", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00675 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00675", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00676 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00676", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00677 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00677", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00678 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00678", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00679 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00679", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00680 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00680", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00681 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00681", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00682 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00682", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00683 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00683", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00684 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00684", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00685 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00685", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00686 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00686", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00687 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00687", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00688 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00688", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00689 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00689", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00690 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00690", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VOSCE16_00691 {
            get {
                object obj = ResourceManager.GetObject("VOSCE16_00691", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
